def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.PROJECT_ROOT = '../../../'

    bld.env.XCC_FLAGS = [
        '-Os', '-g', '-save-temps', '-report', '-lquadflash', '-fxscope',
        '-DDEBUG_PRINT_ENABLE=1', '-DXASSERT_ENABLE_ASSERTIONS=1',
        '-DXASSERT_ENABLE_DEBUG=1'
    ]

    depends_on = ['lib_filesystem']

    source = bld.path.ant_glob('src/*')
    bld.program(source=source, depends_on=depends_on)
